=== MirantisContainers/mke-release/release-matrix/release-matrix-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MKE 4 Release Compatibility Matrix",
  "description": "",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "mkeReleaseVersion": {
        "description": "The MKE 4 minor/patch version that this entry applies to",
        "type": "string"
      },
      "k0rdentVersion": {
        "description": "K0rdent version for this MKE 4 release",
        "type": "string"
      },
      "mkeOperatorImageVersion": {
        "type": "string",
        "description": "MKE Operator Image version for this MKE 4 release"
      },
      "mkeOperatorChartVersion": {
        "type": "string",
        "description": "MKE Operator Helm Chart version for this MKE 4 release"
      },
      "k0sVersion": {
        "type": "string",
        "description": "k0s version for this MKE 4 release"
      },
      "isLatest": {
        "type": "boolean",
        "description": "Whether this is the latest MKE 4 release"
      },
      "minimumMkectlVersion": {
        "type": "string",
        "description": "Minimum mkectl version required to install this MKE 4 release"
      },
      "network": {
        "type": "object",
        "description": "Network configuration for this MKE 4 release",
        "properties": {
          "calico": {
            "type": "object",
            "description": "Calico network configuration for this MKE 4 release",
            "properties": {
              "oss": {
                "type": "object",
                "description": "Calico OSS network configuration for this MKE 4 release",
                "properties": {
                  "version": {
                    "type": "string",
                    "description": "version for Calico OSS for this MKE 4 release"
                  }
                },
                "required": ["version"]
              }
            },
            "required": ["oss"]
          }
        },
        "required": ["calico"]
      }
    },
    "required": ["mkeReleaseVersion", "k0rdentVersion", "mkeOperatorImageVersion", "mkeOperatorChartVersion", "k0sVersion", "network" ,"minimumMkectlVersion"]
  }
}

=== MirantisContainers/mke-release/release-matrix/release-matrix.json
[
  {
    "mkeReleaseVersion": "v4.2.0-beta.2",
    "k0rdentVersion": "1.3.2",
    "mkeOperatorImageVersion": "v1.7.2",
    "mkeOperatorChartVersion": "3.19.21",
    "k0sVersion": "v1.35.4+k0s.1",
    "isLatest": false,
    "minimumMkectlVersion": "v4.2.0-beta.2",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.31.500"
        }
      }
    }
  },
  {
    "mkeReleaseVersion": "v4.1.5",
    "k0rdentVersion": "1.2.3",
    "mkeOperatorImageVersion": "v1.6.3",
    "mkeOperatorChartVersion": "3.17.2",
    "k0sVersion": "v1.32.11+k0s.0",
    "isLatest": true,
    "minimumMkectlVersion": "v4.1.5",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.30.200"
        }
      }
    }
  },
  {
    "mkeReleaseVersion": "v4.1.3",
    "k0rdentVersion": "1.2.3",
    "mkeOperatorImageVersion": "v1.6.1",
    "mkeOperatorChartVersion": "3.17.1",
    "k0sVersion": "v1.32.11+k0s.0",
    "isLatest": true,
    "minimumMkectlVersion": "v4.1.3",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.30.200"
        }
      }
    }
  },
  {
    "mkeReleaseVersion": "v4.1.2",
    "k0rdentVersion": "1.1.0",
    "mkeOperatorImageVersion": "v1.4.15",
    "mkeOperatorChartVersion": "3.11.2",
    "k0sVersion": "v1.32.6+k0s.0",
    "isLatest": false,
    "minimumMkectlVersion": "v4.1.2",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.30.200"
        }
      }
    }
  },
  {
    "mkeReleaseVersion": "v4.1.1",
    "k0rdentVersion": "1.1.0",
    "mkeOperatorImageVersion": "v1.4.5",
    "mkeOperatorChartVersion": "3.4.1",
    "k0sVersion": "v1.32.6+k0s.0",
    "isLatest": false,
    "minimumMkectlVersion": "v4.1.1",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.30.200"
        }
      }
    }
  },
  {
    "mkeReleaseVersion": "v4.1.0",
    "k0rdentVersion": "0.2.0-alpha4",
    "mkeOperatorImageVersion": "v1.3.0",
    "mkeOperatorChartVersion": "1.0.0",
    "calicoOSSVersion": "v3.29.3",
    "k0sVersion": "v1.32.3+k0s.0",
    "isLatest": false,
    "minimumMkectlVersion": "v4.1.0",
    "network": {
      "calico": {
        "oss": {
          "version": "v3.29.3"
        }
      }
    }
  }
]
